parameters:
  currency_spreads:

    EUR:
      buySpread: 0.05
      sellSpread: 0.07

    USD:
      buySpread: 0.05
      sellSpread: 0.07

    CZK:
      sellSpread: 0.15

    IDR:
      sellSpread: 0.15

    BRL:
      sellSpread: 0.15
