version: '3.8'
services:

  webserver:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    volumes:
      - .:/var/www/html
    command: ["bash", "/var/www/html/docker/web/init.sh"]
    container_name: recruitment-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
      - APACHE_DOCUMENT_ROOT=/var/www/html/public