#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\UI\Web\DefaultController::setupCheck

exchange_rates.list:
    path: /api/v1/exchange-rates
    controller: App\UI\Api\Action\GetExchangeRatesList

index:
    path: /{wildcard}
    defaults: {
        _controller: App\UI\Web\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index

