setupcheck:
  path: /api/setup-check
  controller: App\Presentation\Controller\DefaultController::setupCheck

exchangerates:
  path: /api/exchange-rates
  controller: App\Presentation\Controller\ExchangeRatesController


ndex:
  path: /{wildcard}
  defaults: {
    _controller: App\Presentation\Controller\DefaultController::index
  }
  requirements:
    wildcard: .*