#home:
#  path: /
#  defaults: { _controller: 'AppBundle\Controller\DefaultController::indexAction' }
#  methods:  GET
#

setupcheck:
    path: /api/setup-check
    controller: App\Controller\DefaultController::setupCheck

list:
    path: /exchange-rates/{date}
    defaults: {
        _controller: App\Controller\ExchangeRatesController::list
    }

currencyData:
    path: /currencyData/{date}
    defaults: {
        _controller: App\Controller\ExchangeRatesController::getCurrencyData
    }

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*
    # controller: App\Controller\DefaultController::index


